const express = require("express");
const statusMonitor = require('express-status-monitor')();
const dbRoute = require("./core/db.route");
let cli = require("./core/cli.lib");
cli = new cli();
const path = require("path");
let app = express();
let port = process.env.PORT || 3000;
app.use(statusMonitor);
app.use('/db', dbRoute.router);
app.get('/status', statusMonitor.pageRoute);
app.use("/", express.static(path.join(__dirname, "..", "frontend", "dist")));
cli.cli.context.db = dbRoute.db;
cli.cli.context.database = dbRoute.db.db;
app.listen(port);